"""initial schema

Creates the eleven core tables, every one carrying tenant_id, plus the
append-only enforcement on audit_log.

Revision ID: 2987110e7ed3
Revises:
Create Date: 2026-07-29 18:23:07.516090

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2987110e7ed3"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# --- audit_log append-only enforcement --------------------------------------
# The audit trail is only worth having if it cannot be quietly rewritten. UPDATE
# is refused outright. DELETE is refused unless the session explicitly opts in,
# which is how the PDPL erasure path (Phase 4) still honours a right-to-erasure
# request without leaving casual deletion available to everything else.
#
#     SET LOCAL mawjood.allow_purge = 'on';
#
AUDIT_GUARD_FUNCTION = """
CREATE OR REPLACE FUNCTION mawjood_audit_log_guard() RETURNS trigger AS $$
BEGIN
    IF (TG_OP = 'UPDATE') THEN
        RAISE EXCEPTION
            'audit_log is append-only: UPDATE is not permitted'
            USING ERRCODE = 'check_violation';
    END IF;

    IF (TG_OP = 'DELETE') THEN
        IF current_setting('mawjood.allow_purge', true) IS DISTINCT FROM 'on' THEN
            RAISE EXCEPTION
                'audit_log is append-only: DELETE requires mawjood.allow_purge'
                USING ERRCODE = 'check_violation';
        END IF;
        RETURN OLD;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

AUDIT_GUARD_TRIGGER = """
CREATE TRIGGER audit_log_append_only
BEFORE UPDATE OR DELETE ON audit_log
FOR EACH ROW EXECUTE FUNCTION mawjood_audit_log_guard();
"""


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("default_locale", sa.String(length=8), server_default="en", nullable=False),
        sa.Column("timezone", sa.String(length=64), server_default="Asia/Dubai", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
        sa.UniqueConstraint("slug", name=op.f("uq_tenants_slug")),
    )
    op.create_index(op.f("ix_tenants_created_at"), "tenants", ["created_at"], unique=False)
    op.create_table(
        "leads",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("wa_id", sa.String(length=64), nullable=False),
        sa.Column("phone_e164", sa.String(length=32), nullable=True),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("locale", sa.String(length=8), server_default="en", nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_leads_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leads")),
        sa.UniqueConstraint("tenant_id", "wa_id", name="uq_leads_tenant_id_wa_id"),
    )
    op.create_index(op.f("ix_leads_created_at"), "leads", ["created_at"], unique=False)
    op.create_index(op.f("ix_leads_tenant_id"), "leads", ["tenant_id"], unique=False)
    op.create_index(
        "ix_leads_tenant_id_last_seen_at", "leads", ["tenant_id", "last_seen_at"], unique=False
    )
    op.create_table(
        "routing_config",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "salon",
                "spa",
                "restaurant",
                "food_delivery",
                "ride",
                "other",
                name="category",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("platform_slug", sa.String(length=64), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "position >= 0", name=op.f("ck_routing_config_position_is_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_routing_config_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_routing_config")),
        sa.UniqueConstraint(
            "tenant_id", "category", "platform_slug", name="uq_routing_config_tenant_category_slug"
        ),
        sa.UniqueConstraint(
            "tenant_id", "category", "position", name="uq_routing_config_tenant_category_position"
        ),
    )
    op.create_index(
        op.f("ix_routing_config_created_at"), "routing_config", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_routing_config_tenant_id"), "routing_config", ["tenant_id"], unique=False
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column(
            "channel",
            sa.Enum("whatsapp", "console", name="channel", native_enum=False, length=48),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "awaiting_handoff",
                "handed_off",
                "closed",
                name="conversation_status",
                native_enum=False,
                length=48,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("locale", sa.String(length=8), server_default="en", nullable=False),
        sa.Column("bot_muted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_activity_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
            name=op.f("fk_conversations_lead_id_leads"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_conversations_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
    )
    op.create_index(
        op.f("ix_conversations_created_at"), "conversations", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_conversations_last_activity_at"),
        "conversations",
        ["last_activity_at"],
        unique=False,
    )
    op.create_index(op.f("ix_conversations_lead_id"), "conversations", ["lead_id"], unique=False)
    op.create_index(
        op.f("ix_conversations_tenant_id"), "conversations", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_conversations_tenant_id_lead_id_status",
        "conversations",
        ["tenant_id", "lead_id", "status"],
        unique=False,
    )
    op.create_table(
        "attribution",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("source_code", sa.String(length=64), nullable=False),
        sa.Column(
            "medium",
            sa.Enum(
                "wa_link",
                "qr",
                "direct",
                "unknown",
                name="attribution_medium",
                native_enum=False,
                length=48,
            ),
            server_default="unknown",
            nullable=False,
        ),
        sa.Column("is_first_touch", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("raw_payload", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_attribution_conversation_id_conversations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_attribution_lead_id_leads"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_attribution_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attribution")),
    )
    op.create_index(op.f("ix_attribution_created_at"), "attribution", ["created_at"], unique=False)
    op.create_index(op.f("ix_attribution_lead_id"), "attribution", ["lead_id"], unique=False)
    op.create_index(
        op.f("ix_attribution_source_code"), "attribution", ["source_code"], unique=False
    )
    op.create_index(op.f("ix_attribution_tenant_id"), "attribution", ["tenant_id"], unique=False)
    op.create_index(
        "ix_attribution_tenant_id_source_code",
        "attribution",
        ["tenant_id", "source_code"],
        unique=False,
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("turn_id", sa.UUID(), nullable=True),
        sa.Column("decision_id", sa.UUID(), nullable=True),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("lead_id", sa.UUID(), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.String(length=32), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=True),
        sa.Column("platform_slug", sa.String(length=64), nullable=True),
        sa.Column("merchant_ref", sa.String(length=200), nullable=True),
        sa.Column("attempt_number", sa.Integer(), nullable=True),
        sa.Column("outcome", sa.String(length=48), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("advance_reason", sa.String(length=200), nullable=True),
        sa.Column("consumer_visible", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("phrasebank_key", sa.String(length=128), nullable=True),
        sa.Column("locale", sa.String(length=8), nullable=True),
        sa.Column("consumer_text", sa.Text(), nullable=True),
        sa.Column(
            "inputs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("schema_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_audit_log_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_audit_log_lead_id_leads"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_audit_log_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
        sa.UniqueConstraint("seq", name=op.f("uq_audit_log_seq")),
    )
    op.create_index(
        op.f("ix_audit_log_consumer_visible"), "audit_log", ["consumer_visible"], unique=False
    )
    op.create_index(
        op.f("ix_audit_log_correlation_id"), "audit_log", ["correlation_id"], unique=False
    )
    op.create_index(op.f("ix_audit_log_decision_id"), "audit_log", ["decision_id"], unique=False)
    op.create_index(
        "ix_audit_log_details", "audit_log", ["details"], unique=False, postgresql_using="gin"
    )
    op.create_index(op.f("ix_audit_log_occurred_at"), "audit_log", ["occurred_at"], unique=False)
    op.create_index(op.f("ix_audit_log_tenant_id"), "audit_log", ["tenant_id"], unique=False)
    op.create_index(
        "ix_audit_log_tenant_id_conversation_id_seq",
        "audit_log",
        ["tenant_id", "conversation_id", "seq"],
        unique=False,
    )
    op.create_index(
        "ix_audit_log_tenant_id_event_type_occurred_at",
        "audit_log",
        ["tenant_id", "event_type", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_log_tenant_id_occurred_at",
        "audit_log",
        ["tenant_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_log_tenant_id_platform_slug_outcome",
        "audit_log",
        ["tenant_id", "platform_slug", "outcome"],
        unique=False,
    )
    op.create_index(op.f("ix_audit_log_turn_id"), "audit_log", ["turn_id"], unique=False)
    op.create_table(
        "bookings",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "salon",
                "spa",
                "restaurant",
                "food_delivery",
                "ride",
                "other",
                name="category",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("platform_slug", sa.String(length=64), nullable=False),
        sa.Column("merchant_ref", sa.String(length=200), nullable=True),
        sa.Column("external_booking_ref", sa.String(length=200), nullable=True),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "confirmed",
                "uncertain",
                "cancelled",
                "failed",
                name="booking_status",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("slot_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("slot_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("venue_name", sa.String(length=200), nullable=True),
        sa.Column("price_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("price_currency", sa.String(length=3), nullable=True),
        sa.Column(
            "payment_status",
            sa.Enum(
                "not_applicable",
                "pay_at_venue",
                "pending",
                "paid",
                "refunded",
                name="payment_status",
                native_enum=False,
                length=48,
            ),
            server_default="not_applicable",
            nullable=False,
        ),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_bookings_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_bookings_lead_id_leads"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_bookings_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookings")),
        sa.UniqueConstraint(
            "tenant_id", "idempotency_key", name="uq_bookings_tenant_id_idempotency_key"
        ),
    )
    op.create_index(
        op.f("ix_bookings_conversation_id"), "bookings", ["conversation_id"], unique=False
    )
    op.create_index(op.f("ix_bookings_created_at"), "bookings", ["created_at"], unique=False)
    op.create_index(op.f("ix_bookings_lead_id"), "bookings", ["lead_id"], unique=False)
    op.create_index(op.f("ix_bookings_tenant_id"), "bookings", ["tenant_id"], unique=False)
    op.create_index(
        "ix_bookings_tenant_id_status_slot_start",
        "bookings",
        ["tenant_id", "status", "slot_start"],
        unique=False,
    )
    op.create_table(
        "handoff_queue",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column(
            "reason",
            sa.Enum(
                "cascade_exhausted",
                "unsupported_action",
                "reconciliation_inconclusive",
                "consumer_request",
                "consent_withdrawn",
                "system_error",
                name="handoff_reason",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "claimed",
                "resolved",
                "abandoned",
                name="handoff_status",
                native_enum=False,
                length=48,
            ),
            server_default="open",
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), server_default="0", nullable=False),
        sa.Column("claimed_by", sa.String(length=200), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "context",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_handoff_queue_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
            name=op.f("fk_handoff_queue_lead_id_leads"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_handoff_queue_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_handoff_queue")),
    )
    op.create_index(
        op.f("ix_handoff_queue_conversation_id"), "handoff_queue", ["conversation_id"], unique=False
    )
    op.create_index(
        op.f("ix_handoff_queue_created_at"), "handoff_queue", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_handoff_queue_tenant_id"), "handoff_queue", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_handoff_queue_tenant_id_status_priority",
        "handoff_queue",
        ["tenant_id", "status", "priority"],
        unique=False,
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("seq", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("turn_id", sa.UUID(), nullable=False),
        sa.Column(
            "direction",
            sa.Enum("inbound", "outbound", name="direction", native_enum=False, length=48),
            nullable=False,
        ),
        sa.Column(
            "channel",
            sa.Enum("whatsapp", "console", name="channel", native_enum=False, length=48),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "received",
                "queued",
                "sent",
                "delivered",
                "read",
                "failed",
                name="message_status",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("locale", sa.String(length=8), server_default="en", nullable=False),
        sa.Column("phrasebank_key", sa.String(length=128), nullable=True),
        sa.Column("provider_message_id", sa.String(length=200), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(direction <> 'outbound') OR (phrasebank_key IS NOT NULL)",
            name=op.f("ck_messages_outbound_messages_come_from_the_phrasebank"),
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_messages_lead_id_leads"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_messages_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sa.UniqueConstraint("seq", name=op.f("uq_messages_seq")),
    )
    op.create_index(
        op.f("ix_messages_conversation_id"), "messages", ["conversation_id"], unique=False
    )
    op.create_index(
        "ix_messages_conversation_id_seq", "messages", ["conversation_id", "seq"], unique=False
    )
    op.create_index(op.f("ix_messages_created_at"), "messages", ["created_at"], unique=False)
    op.create_index(op.f("ix_messages_tenant_id"), "messages", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_messages_turn_id"), "messages", ["turn_id"], unique=False)
    op.create_index(
        "uq_messages_tenant_id_channel_provider_message_id",
        "messages",
        ["tenant_id", "channel", "provider_message_id"],
        unique=True,
        postgresql_where=sa.text("provider_message_id IS NOT NULL"),
    )
    op.create_table(
        "consents",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column(
            "event",
            sa.Enum(
                "notice_shown",
                "granted",
                "withdrawn",
                name="consent_event",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("policy_version", sa.String(length=32), nullable=False),
        sa.Column("wording", sa.Text(), nullable=False),
        sa.Column("locale", sa.String(length=8), nullable=False),
        sa.Column(
            "channel",
            sa.Enum("whatsapp", "console", name="channel", native_enum=False, length=48),
            nullable=False,
        ),
        sa.Column("evidence_message_id", sa.UUID(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_consents_conversation_id_conversations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_message_id"],
            ["messages.id"],
            name=op.f("fk_consents_evidence_message_id_messages"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_consents_lead_id_leads"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_consents_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_consents")),
    )
    op.create_index(op.f("ix_consents_created_at"), "consents", ["created_at"], unique=False)
    op.create_index(op.f("ix_consents_lead_id"), "consents", ["lead_id"], unique=False)
    op.create_index(op.f("ix_consents_occurred_at"), "consents", ["occurred_at"], unique=False)
    op.create_index(op.f("ix_consents_tenant_id"), "consents", ["tenant_id"], unique=False)
    op.create_index(
        "ix_consents_tenant_id_lead_id_occurred_at",
        "consents",
        ["tenant_id", "lead_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "feedback",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("booking_id", sa.UUID(), nullable=True),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "rating IS NULL OR (rating BETWEEN 1 AND 5)",
            name=op.f("ck_feedback_rating_is_one_to_five"),
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk_feedback_booking_id_bookings"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_feedback_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_feedback_lead_id_leads"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_feedback_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feedback")),
    )
    op.create_index(op.f("ix_feedback_created_at"), "feedback", ["created_at"], unique=False)
    op.create_index(op.f("ix_feedback_lead_id"), "feedback", ["lead_id"], unique=False)
    op.create_index(op.f("ix_feedback_tenant_id"), "feedback", ["tenant_id"], unique=False)
    # ### end Alembic commands ###

    op.execute(AUDIT_GUARD_FUNCTION)
    op.execute(AUDIT_GUARD_TRIGGER)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS audit_log_append_only ON audit_log")
    op.execute("DROP FUNCTION IF EXISTS mawjood_audit_log_guard()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_feedback_tenant_id"), table_name="feedback")
    op.drop_index(op.f("ix_feedback_lead_id"), table_name="feedback")
    op.drop_index(op.f("ix_feedback_created_at"), table_name="feedback")
    op.drop_table("feedback")
    op.drop_index("ix_consents_tenant_id_lead_id_occurred_at", table_name="consents")
    op.drop_index(op.f("ix_consents_tenant_id"), table_name="consents")
    op.drop_index(op.f("ix_consents_occurred_at"), table_name="consents")
    op.drop_index(op.f("ix_consents_lead_id"), table_name="consents")
    op.drop_index(op.f("ix_consents_created_at"), table_name="consents")
    op.drop_table("consents")
    op.drop_index(
        "uq_messages_tenant_id_channel_provider_message_id",
        table_name="messages",
        postgresql_where=sa.text("provider_message_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_messages_turn_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_tenant_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_created_at"), table_name="messages")
    op.drop_index("ix_messages_conversation_id_seq", table_name="messages")
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index("ix_handoff_queue_tenant_id_status_priority", table_name="handoff_queue")
    op.drop_index(op.f("ix_handoff_queue_tenant_id"), table_name="handoff_queue")
    op.drop_index(op.f("ix_handoff_queue_created_at"), table_name="handoff_queue")
    op.drop_index(op.f("ix_handoff_queue_conversation_id"), table_name="handoff_queue")
    op.drop_table("handoff_queue")
    op.drop_index("ix_bookings_tenant_id_status_slot_start", table_name="bookings")
    op.drop_index(op.f("ix_bookings_tenant_id"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_lead_id"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_created_at"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_conversation_id"), table_name="bookings")
    op.drop_table("bookings")
    op.drop_index(op.f("ix_audit_log_turn_id"), table_name="audit_log")
    op.drop_index("ix_audit_log_tenant_id_platform_slug_outcome", table_name="audit_log")
    op.drop_index("ix_audit_log_tenant_id_occurred_at", table_name="audit_log")
    op.drop_index("ix_audit_log_tenant_id_event_type_occurred_at", table_name="audit_log")
    op.drop_index("ix_audit_log_tenant_id_conversation_id_seq", table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_tenant_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_occurred_at"), table_name="audit_log")
    op.drop_index("ix_audit_log_details", table_name="audit_log", postgresql_using="gin")
    op.drop_index(op.f("ix_audit_log_decision_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_correlation_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_consumer_visible"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index("ix_attribution_tenant_id_source_code", table_name="attribution")
    op.drop_index(op.f("ix_attribution_tenant_id"), table_name="attribution")
    op.drop_index(op.f("ix_attribution_source_code"), table_name="attribution")
    op.drop_index(op.f("ix_attribution_lead_id"), table_name="attribution")
    op.drop_index(op.f("ix_attribution_created_at"), table_name="attribution")
    op.drop_table("attribution")
    op.drop_index("ix_conversations_tenant_id_lead_id_status", table_name="conversations")
    op.drop_index(op.f("ix_conversations_tenant_id"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_lead_id"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_last_activity_at"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_created_at"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_index(op.f("ix_routing_config_tenant_id"), table_name="routing_config")
    op.drop_index(op.f("ix_routing_config_created_at"), table_name="routing_config")
    op.drop_table("routing_config")
    op.drop_index("ix_leads_tenant_id_last_seen_at", table_name="leads")
    op.drop_index(op.f("ix_leads_tenant_id"), table_name="leads")
    op.drop_index(op.f("ix_leads_created_at"), table_name="leads")
    op.drop_table("leads")
    op.drop_index(op.f("ix_tenants_created_at"), table_name="tenants")
    op.drop_table("tenants")
    # ### end Alembic commands ###
