"""scheduled notifications

Reminders, the follow-up and the satisfaction ask become rows the moment a
booking is confirmed, rather than in-process timers that die with the process.

The unique constraint on ``(booking_id, kind)`` is the idempotency guarantee. It
lives in the schema rather than in a query the caller must remember, so a
consumer cannot be double-reminded even if two scheduler passes race.

Revision ID: bd6290b7f0ee
Revises: e3fe6d095d50
Create Date: 2026-07-30 11:13:06.727469

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd6290b7f0ee"
down_revision: str | Sequence[str] | None = "e3fe6d095d50"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scheduled_notifications",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("booking_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "reminder_24h",
                "reminder_2h",
                "follow_up",
                "satisfaction",
                name="notification_kind",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "sent",
                "deferred",
                "skipped",
                "failed",
                name="notification_status",
                native_enum=False,
                length=48,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("message_id", sa.UUID(), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("template_name", sa.String(length=128), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
            name=op.f("fk_scheduled_notifications_booking_id_bookings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_scheduled_notifications_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
            name=op.f("fk_scheduled_notifications_lead_id_leads"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_scheduled_notifications_message_id_messages"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_scheduled_notifications_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scheduled_notifications")),
        sa.UniqueConstraint("booking_id", "kind", name="uq_scheduled_notifications_booking_kind"),
    )
    op.create_index(
        op.f("ix_scheduled_notifications_booking_id"),
        "scheduled_notifications",
        ["booking_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduled_notifications_created_at"),
        "scheduled_notifications",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduled_notifications_lead_id"),
        "scheduled_notifications",
        ["lead_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduled_notifications_tenant_id"),
        "scheduled_notifications",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "ix_scheduled_notifications_tenant_status_due",
        "scheduled_notifications",
        ["tenant_id", "status", "due_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_scheduled_notifications_tenant_status_due", table_name="scheduled_notifications"
    )
    op.drop_index(
        op.f("ix_scheduled_notifications_tenant_id"), table_name="scheduled_notifications"
    )
    op.drop_index(op.f("ix_scheduled_notifications_lead_id"), table_name="scheduled_notifications")
    op.drop_index(
        op.f("ix_scheduled_notifications_created_at"), table_name="scheduled_notifications"
    )
    op.drop_index(
        op.f("ix_scheduled_notifications_booking_id"), table_name="scheduled_notifications"
    )
    op.drop_table("scheduled_notifications")
    # ### end Alembic commands ###
