"""conversation state and merchant credentials

Revision ID: e3fe6d095d50
Revises: 2987110e7ed3
Create Date: 2026-07-30 05:30:34.486889

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e3fe6d095d50"
down_revision: str | Sequence[str] | None = "2987110e7ed3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "merchant_credentials",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("platform_slug", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("area", sa.String(length=120), nullable=True),
        sa.Column(
            "external_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("secret_ref", sa.String(length=200), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("priority", sa.Integer(), server_default="0", nullable=False),
        sa.Column("credential_degraded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_merchant_credentials_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_merchant_credentials")),
        sa.UniqueConstraint(
            "tenant_id",
            "platform_slug",
            "display_name",
            name="uq_merchant_credentials_tenant_platform_name",
        ),
    )
    op.create_index(
        op.f("ix_merchant_credentials_created_at"),
        "merchant_credentials",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_merchant_credentials_tenant_id"),
        "merchant_credentials",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "ix_merchant_credentials_tenant_platform_priority",
        "merchant_credentials",
        ["tenant_id", "platform_slug", "priority"],
        unique=False,
    )
    op.add_column(
        "conversations",
        sa.Column("state", sa.String(length=32), server_default="greeting", nullable=False),
    )
    op.add_column(
        "conversations",
        sa.Column(
            "collected_slots",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "conversations",
        sa.Column(
            "pending_offer",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversations", "pending_offer")
    op.drop_column("conversations", "collected_slots")
    op.drop_column("conversations", "state")
    op.drop_index(
        "ix_merchant_credentials_tenant_platform_priority", table_name="merchant_credentials"
    )
    op.drop_index(op.f("ix_merchant_credentials_tenant_id"), table_name="merchant_credentials")
    op.drop_index(op.f("ix_merchant_credentials_created_at"), table_name="merchant_credentials")
    op.drop_table("merchant_credentials")
    # ### end Alembic commands ###
