"""Declarative base, column conventions and shared mixins.

Two conventions matter here and are enforced by mixins rather than by diligence:

* **Every core table carries ``tenant_id``.** Mawjood may later run for several
  operators from one codebase. Adding that column now costs a day; adding it to a
  live schema later is a rewrite. See CLAUDE.md section 6.
* **Every timestamp is timezone-aware.** The UAE is UTC+4 and reminders are
  wall-clock sensitive; a naive timestamp column is a bug waiting for a booking
  to land an hour out.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any, ClassVar

from sqlalchemy import DateTime, ForeignKey, MetaData, String, func, text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PgUUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Predictable constraint names, so migrations can reference them and a failing
# constraint says which one it was.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    type_annotation_map: ClassVar[dict[Any, Any]] = {
        dict[str, Any]: JSONB,
        datetime: DateTime(timezone=True),
    }


def uuid_pk() -> Mapped[uuid.UUID]:
    """UUID primary key generated by the database.

    Server-side so an id exists even for rows inserted outside the application
    (a backfill, a manual fix). PostgreSQL 13+ has gen_random_uuid() built in.
    """
    return mapped_column(
        PgUUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


class TimestampMixin:
    """created_at / updated_at, both maintained by the database."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        index=True,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )


class TenantMixin:
    """The tenant scope carried by every core table.

    ON DELETE CASCADE is deliberate: removing a tenant must not strand rows that
    nothing can reach but that still hold consumer data.
    """

    tenant_id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )


def short_text(length: int = 64) -> Mapped[str]:
    return mapped_column(String(length), nullable=False)


__all__ = ["Base", "TenantMixin", "TimestampMixin", "short_text", "uuid_pk"]
